ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS order_unit VARCHAR(50) DEFAULT '件',
ADD COLUMN IF NOT EXISTS order_unit_size INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS min_order_quantity INTEGER DEFAULT 1;
